version: '3'

services:
    backend:
        image: tyaco-node:latest
        container_name: tyaco_backend

        working_dir: /app

        networks:
            - tyaco-network
        ports:
            - "2020:2020"

        command: npm start

    database:
        image: mongo:latest
        container_name: tyaco_database
        #restart: always
        environment:
            MONGO_INITDB_DATABASE: tyaco

        networks:
            - tyaco-network
        ports:
            - "27017:27017"
        volumes:
            - ./db/init.js:/docker-entrypoint-initdb.d/init.js
            #- ./data:/data/db

networks:
    tyaco-network:

volumes :
    tyaco:
