version: '3'

# TODO : Create a Dockerfile per container, build the images, and link them to the docker-compose with : build: ./dockerFilePath

services:
    node:
        image: tyaco-node:latest
        container_name: tyaco_backend

        working_dir: /app

        networks:
            - tyaco-network
        ports:
            - "2020:2020"

        command: npm start

    mongodb:
        image: mongo:latest
        container_name: tyaco_database
        restart: always
        environment:
            MONGO_INITDB_DATABASE: tyaco

        networks:
            - tyaco-network
        ports:
            - "2021:27017"
        volumes:
            - ./db/init.js:/docker-entrypoint-initdb.d/init.js
            - ./data:/data/db

networks:
    tyaco-network:

volumes :
    tyaco:
